# Generated by Django 3.0 on 2021-03-06 03:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210305_2149'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Fecha de creación'),
            preserve_default=False,
        ),
    ]
